sources:
  - name: mysubgraph
    handler:
      graphql:
        endpoint: http://localhost:8000/subgraphs/name/mynft

plugins:
  - pollingLive:
      defaultInterval: 13000

documents:
  - './queries/**/*.graphql'
  - './mutations/**/*.graphql'

additionalTypeDefs:
  - ./additionalTypeDefs.graphql

additionalResolvers:
  - './resolvers/index.ts'
