sources:
  - name: mysubgraph
    handler:
      graphql:
        endpoint: http://localhost:8000/subgraphs/name/mynft

plugins:
  - pollingLive:
      defaultInterval: 13000

documents:
  - './queries/**/*.graphql'
  - './mutations/**/*.graphql'

additionalTypeDefs: |
  extend schema {
    mutation: Mutation
  }

  type Mutation {
    connect: Boolean!
  }

  extend type Query {
    _ethereum: Ethereum
  }

  type Ethereum {
    account: String
  }

additionalResolvers:
  - './resolvers/index.ts'
